// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: dtos.prot

package ar.com.moviecentral.dtos;

public final class Protos {
  private Protos() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface MovieDTOOrBuilder extends
      // @@protoc_insertion_point(interface_extends:ar.com.moviecentral.dtos.MovieDTO)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required int64 movieId = 1;</code>
     * @return Whether the movieId field is set.
     */
    boolean hasMovieId();
    /**
     * <code>required int64 movieId = 1;</code>
     * @return The movieId.
     */
    long getMovieId();

    /**
     * <code>required string title = 2;</code>
     * @return Whether the title field is set.
     */
    boolean hasTitle();
    /**
     * <code>required string title = 2;</code>
     * @return The title.
     */
    java.lang.String getTitle();
    /**
     * <code>required string title = 2;</code>
     * @return The bytes for title.
     */
    com.google.protobuf.ByteString
        getTitleBytes();

    /**
     * <code>required .google.protobuf.Timestamp date = 3;</code>
     * @return Whether the date field is set.
     */
    boolean hasDate();
    /**
     * <code>required .google.protobuf.Timestamp date = 3;</code>
     * @return The date.
     */
    com.google.protobuf.Timestamp getDate();
    /**
     * <code>required .google.protobuf.Timestamp date = 3;</code>
     */
    com.google.protobuf.TimestampOrBuilder getDateOrBuilder();

    /**
     * <code>repeated .ar.com.moviecentral.dtos.MovieDTO.ActorDTO actors = 4;</code>
     */
    java.util.List<ar.com.moviecentral.dtos.Protos.MovieDTO.ActorDTO> 
        getActorsList();
    /**
     * <code>repeated .ar.com.moviecentral.dtos.MovieDTO.ActorDTO actors = 4;</code>
     */
    ar.com.moviecentral.dtos.Protos.MovieDTO.ActorDTO getActors(int index);
    /**
     * <code>repeated .ar.com.moviecentral.dtos.MovieDTO.ActorDTO actors = 4;</code>
     */
    int getActorsCount();
    /**
     * <code>repeated .ar.com.moviecentral.dtos.MovieDTO.ActorDTO actors = 4;</code>
     */
    java.util.List<? extends ar.com.moviecentral.dtos.Protos.MovieDTO.ActorDTOOrBuilder> 
        getActorsOrBuilderList();
    /**
     * <code>repeated .ar.com.moviecentral.dtos.MovieDTO.ActorDTO actors = 4;</code>
     */
    ar.com.moviecentral.dtos.Protos.MovieDTO.ActorDTOOrBuilder getActorsOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code ar.com.moviecentral.dtos.MovieDTO}
   */
  public  static final class MovieDTO extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:ar.com.moviecentral.dtos.MovieDTO)
      MovieDTOOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use MovieDTO.newBuilder() to construct.
    private MovieDTO(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private MovieDTO() {
      title_ = "";
      actors_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new MovieDTO();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private MovieDTO(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              bitField0_ |= 0x00000001;
              movieId_ = input.readInt64();
              break;
            }
            case 18: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000002;
              title_ = bs;
              break;
            }
            case 26: {
              com.google.protobuf.Timestamp.Builder subBuilder = null;
              if (((bitField0_ & 0x00000004) != 0)) {
                subBuilder = date_.toBuilder();
              }
              date_ = input.readMessage(com.google.protobuf.Timestamp.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(date_);
                date_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000004;
              break;
            }
            case 34: {
              if (!((mutable_bitField0_ & 0x00000008) != 0)) {
                actors_ = new java.util.ArrayList<ar.com.moviecentral.dtos.Protos.MovieDTO.ActorDTO>();
                mutable_bitField0_ |= 0x00000008;
              }
              actors_.add(
                  input.readMessage(ar.com.moviecentral.dtos.Protos.MovieDTO.ActorDTO.PARSER, extensionRegistry));
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000008) != 0)) {
          actors_ = java.util.Collections.unmodifiableList(actors_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return ar.com.moviecentral.dtos.Protos.internal_static_ar_com_moviecentral_dtos_MovieDTO_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return ar.com.moviecentral.dtos.Protos.internal_static_ar_com_moviecentral_dtos_MovieDTO_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              ar.com.moviecentral.dtos.Protos.MovieDTO.class, ar.com.moviecentral.dtos.Protos.MovieDTO.Builder.class);
    }

    public interface ActorDTOOrBuilder extends
        // @@protoc_insertion_point(interface_extends:ar.com.moviecentral.dtos.MovieDTO.ActorDTO)
        com.google.protobuf.MessageOrBuilder {

      /**
       * <code>required int64 id = 1;</code>
       * @return Whether the id field is set.
       */
      boolean hasId();
      /**
       * <code>required int64 id = 1;</code>
       * @return The id.
       */
      long getId();

      /**
       * <code>required string firstName = 2;</code>
       * @return Whether the firstName field is set.
       */
      boolean hasFirstName();
      /**
       * <code>required string firstName = 2;</code>
       * @return The firstName.
       */
      java.lang.String getFirstName();
      /**
       * <code>required string firstName = 2;</code>
       * @return The bytes for firstName.
       */
      com.google.protobuf.ByteString
          getFirstNameBytes();

      /**
       * <code>required string lastName = 3;</code>
       * @return Whether the lastName field is set.
       */
      boolean hasLastName();
      /**
       * <code>required string lastName = 3;</code>
       * @return The lastName.
       */
      java.lang.String getLastName();
      /**
       * <code>required string lastName = 3;</code>
       * @return The bytes for lastName.
       */
      com.google.protobuf.ByteString
          getLastNameBytes();
    }
    /**
     * Protobuf type {@code ar.com.moviecentral.dtos.MovieDTO.ActorDTO}
     */
    public  static final class ActorDTO extends
        com.google.protobuf.GeneratedMessageV3 implements
        // @@protoc_insertion_point(message_implements:ar.com.moviecentral.dtos.MovieDTO.ActorDTO)
        ActorDTOOrBuilder {
    private static final long serialVersionUID = 0L;
      // Use ActorDTO.newBuilder() to construct.
      private ActorDTO(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
        super(builder);
      }
      private ActorDTO() {
        firstName_ = "";
        lastName_ = "";
      }

      @java.lang.Override
      @SuppressWarnings({"unused"})
      protected java.lang.Object newInstance(
          UnusedPrivateParameter unused) {
        return new ActorDTO();
      }

      @java.lang.Override
      public final com.google.protobuf.UnknownFieldSet
      getUnknownFields() {
        return this.unknownFields;
      }
      private ActorDTO(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        this();
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        int mutable_bitField0_ = 0;
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
            com.google.protobuf.UnknownFieldSet.newBuilder();
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 8: {
                bitField0_ |= 0x00000001;
                id_ = input.readInt64();
                break;
              }
              case 18: {
                com.google.protobuf.ByteString bs = input.readBytes();
                bitField0_ |= 0x00000002;
                firstName_ = bs;
                break;
              }
              case 26: {
                com.google.protobuf.ByteString bs = input.readBytes();
                bitField0_ |= 0x00000004;
                lastName_ = bs;
                break;
              }
              default: {
                if (!parseUnknownField(
                    input, unknownFields, extensionRegistry, tag)) {
                  done = true;
                }
                break;
              }
            }
          }
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(this);
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(
              e).setUnfinishedMessage(this);
        } finally {
          this.unknownFields = unknownFields.build();
          makeExtensionsImmutable();
        }
      }
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return ar.com.moviecentral.dtos.Protos.internal_static_ar_com_moviecentral_dtos_MovieDTO_ActorDTO_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return ar.com.moviecentral.dtos.Protos.internal_static_ar_com_moviecentral_dtos_MovieDTO_ActorDTO_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                ar.com.moviecentral.dtos.Protos.MovieDTO.ActorDTO.class, ar.com.moviecentral.dtos.Protos.MovieDTO.ActorDTO.Builder.class);
      }

      private int bitField0_;
      public static final int ID_FIELD_NUMBER = 1;
      private long id_;
      /**
       * <code>required int64 id = 1;</code>
       * @return Whether the id field is set.
       */
      public boolean hasId() {
        return ((bitField0_ & 0x00000001) != 0);
      }
      /**
       * <code>required int64 id = 1;</code>
       * @return The id.
       */
      public long getId() {
        return id_;
      }

      public static final int FIRSTNAME_FIELD_NUMBER = 2;
      private volatile java.lang.Object firstName_;
      /**
       * <code>required string firstName = 2;</code>
       * @return Whether the firstName field is set.
       */
      public boolean hasFirstName() {
        return ((bitField0_ & 0x00000002) != 0);
      }
      /**
       * <code>required string firstName = 2;</code>
       * @return The firstName.
       */
      public java.lang.String getFirstName() {
        java.lang.Object ref = firstName_;
        if (ref instanceof java.lang.String) {
          return (java.lang.String) ref;
        } else {
          com.google.protobuf.ByteString bs = 
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            firstName_ = s;
          }
          return s;
        }
      }
      /**
       * <code>required string firstName = 2;</code>
       * @return The bytes for firstName.
       */
      public com.google.protobuf.ByteString
          getFirstNameBytes() {
        java.lang.Object ref = firstName_;
        if (ref instanceof java.lang.String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          firstName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }

      public static final int LASTNAME_FIELD_NUMBER = 3;
      private volatile java.lang.Object lastName_;
      /**
       * <code>required string lastName = 3;</code>
       * @return Whether the lastName field is set.
       */
      public boolean hasLastName() {
        return ((bitField0_ & 0x00000004) != 0);
      }
      /**
       * <code>required string lastName = 3;</code>
       * @return The lastName.
       */
      public java.lang.String getLastName() {
        java.lang.Object ref = lastName_;
        if (ref instanceof java.lang.String) {
          return (java.lang.String) ref;
        } else {
          com.google.protobuf.ByteString bs = 
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            lastName_ = s;
          }
          return s;
        }
      }
      /**
       * <code>required string lastName = 3;</code>
       * @return The bytes for lastName.
       */
      public com.google.protobuf.ByteString
          getLastNameBytes() {
        java.lang.Object ref = lastName_;
        if (ref instanceof java.lang.String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          lastName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }

      private byte memoizedIsInitialized = -1;
      @java.lang.Override
      public final boolean isInitialized() {
        byte isInitialized = memoizedIsInitialized;
        if (isInitialized == 1) return true;
        if (isInitialized == 0) return false;

        if (!hasId()) {
          memoizedIsInitialized = 0;
          return false;
        }
        if (!hasFirstName()) {
          memoizedIsInitialized = 0;
          return false;
        }
        if (!hasLastName()) {
          memoizedIsInitialized = 0;
          return false;
        }
        memoizedIsInitialized = 1;
        return true;
      }

      @java.lang.Override
      public void writeTo(com.google.protobuf.CodedOutputStream output)
                          throws java.io.IOException {
        if (((bitField0_ & 0x00000001) != 0)) {
          output.writeInt64(1, id_);
        }
        if (((bitField0_ & 0x00000002) != 0)) {
          com.google.protobuf.GeneratedMessageV3.writeString(output, 2, firstName_);
        }
        if (((bitField0_ & 0x00000004) != 0)) {
          com.google.protobuf.GeneratedMessageV3.writeString(output, 3, lastName_);
        }
        unknownFields.writeTo(output);
      }

      @java.lang.Override
      public int getSerializedSize() {
        int size = memoizedSize;
        if (size != -1) return size;

        size = 0;
        if (((bitField0_ & 0x00000001) != 0)) {
          size += com.google.protobuf.CodedOutputStream
            .computeInt64Size(1, id_);
        }
        if (((bitField0_ & 0x00000002) != 0)) {
          size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, firstName_);
        }
        if (((bitField0_ & 0x00000004) != 0)) {
          size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, lastName_);
        }
        size += unknownFields.getSerializedSize();
        memoizedSize = size;
        return size;
      }

      @java.lang.Override
      public boolean equals(final java.lang.Object obj) {
        if (obj == this) {
         return true;
        }
        if (!(obj instanceof ar.com.moviecentral.dtos.Protos.MovieDTO.ActorDTO)) {
          return super.equals(obj);
        }
        ar.com.moviecentral.dtos.Protos.MovieDTO.ActorDTO other = (ar.com.moviecentral.dtos.Protos.MovieDTO.ActorDTO) obj;

        if (hasId() != other.hasId()) return false;
        if (hasId()) {
          if (getId()
              != other.getId()) return false;
        }
        if (hasFirstName() != other.hasFirstName()) return false;
        if (hasFirstName()) {
          if (!getFirstName()
              .equals(other.getFirstName())) return false;
        }
        if (hasLastName() != other.hasLastName()) return false;
        if (hasLastName()) {
          if (!getLastName()
              .equals(other.getLastName())) return false;
        }
        if (!unknownFields.equals(other.unknownFields)) return false;
        return true;
      }

      @java.lang.Override
      public int hashCode() {
        if (memoizedHashCode != 0) {
          return memoizedHashCode;
        }
        int hash = 41;
        hash = (19 * hash) + getDescriptor().hashCode();
        if (hasId()) {
          hash = (37 * hash) + ID_FIELD_NUMBER;
          hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
              getId());
        }
        if (hasFirstName()) {
          hash = (37 * hash) + FIRSTNAME_FIELD_NUMBER;
          hash = (53 * hash) + getFirstName().hashCode();
        }
        if (hasLastName()) {
          hash = (37 * hash) + LASTNAME_FIELD_NUMBER;
          hash = (53 * hash) + getLastName().hashCode();
        }
        hash = (29 * hash) + unknownFields.hashCode();
        memoizedHashCode = hash;
        return hash;
      }

      public static ar.com.moviecentral.dtos.Protos.MovieDTO.ActorDTO parseFrom(
          java.nio.ByteBuffer data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static ar.com.moviecentral.dtos.Protos.MovieDTO.ActorDTO parseFrom(
          java.nio.ByteBuffer data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static ar.com.moviecentral.dtos.Protos.MovieDTO.ActorDTO parseFrom(
          com.google.protobuf.ByteString data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static ar.com.moviecentral.dtos.Protos.MovieDTO.ActorDTO parseFrom(
          com.google.protobuf.ByteString data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static ar.com.moviecentral.dtos.Protos.MovieDTO.ActorDTO parseFrom(byte[] data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static ar.com.moviecentral.dtos.Protos.MovieDTO.ActorDTO parseFrom(
          byte[] data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static ar.com.moviecentral.dtos.Protos.MovieDTO.ActorDTO parseFrom(java.io.InputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input);
      }
      public static ar.com.moviecentral.dtos.Protos.MovieDTO.ActorDTO parseFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input, extensionRegistry);
      }
      public static ar.com.moviecentral.dtos.Protos.MovieDTO.ActorDTO parseDelimitedFrom(java.io.InputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseDelimitedWithIOException(PARSER, input);
      }
      public static ar.com.moviecentral.dtos.Protos.MovieDTO.ActorDTO parseDelimitedFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
      }
      public static ar.com.moviecentral.dtos.Protos.MovieDTO.ActorDTO parseFrom(
          com.google.protobuf.CodedInputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input);
      }
      public static ar.com.moviecentral.dtos.Protos.MovieDTO.ActorDTO parseFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input, extensionRegistry);
      }

      @java.lang.Override
      public Builder newBuilderForType() { return newBuilder(); }
      public static Builder newBuilder() {
        return DEFAULT_INSTANCE.toBuilder();
      }
      public static Builder newBuilder(ar.com.moviecentral.dtos.Protos.MovieDTO.ActorDTO prototype) {
        return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
      }
      @java.lang.Override
      public Builder toBuilder() {
        return this == DEFAULT_INSTANCE
            ? new Builder() : new Builder().mergeFrom(this);
      }

      @java.lang.Override
      protected Builder newBuilderForType(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        Builder builder = new Builder(parent);
        return builder;
      }
      /**
       * Protobuf type {@code ar.com.moviecentral.dtos.MovieDTO.ActorDTO}
       */
      public static final class Builder extends
          com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
          // @@protoc_insertion_point(builder_implements:ar.com.moviecentral.dtos.MovieDTO.ActorDTO)
          ar.com.moviecentral.dtos.Protos.MovieDTO.ActorDTOOrBuilder {
        public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
          return ar.com.moviecentral.dtos.Protos.internal_static_ar_com_moviecentral_dtos_MovieDTO_ActorDTO_descriptor;
        }

        @java.lang.Override
        protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internalGetFieldAccessorTable() {
          return ar.com.moviecentral.dtos.Protos.internal_static_ar_com_moviecentral_dtos_MovieDTO_ActorDTO_fieldAccessorTable
              .ensureFieldAccessorsInitialized(
                  ar.com.moviecentral.dtos.Protos.MovieDTO.ActorDTO.class, ar.com.moviecentral.dtos.Protos.MovieDTO.ActorDTO.Builder.class);
        }

        // Construct using ar.com.moviecentral.dtos.Protos.MovieDTO.ActorDTO.newBuilder()
        private Builder() {
          maybeForceBuilderInitialization();
        }

        private Builder(
            com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
          super(parent);
          maybeForceBuilderInitialization();
        }
        private void maybeForceBuilderInitialization() {
          if (com.google.protobuf.GeneratedMessageV3
                  .alwaysUseFieldBuilders) {
          }
        }
        @java.lang.Override
        public Builder clear() {
          super.clear();
          id_ = 0L;
          bitField0_ = (bitField0_ & ~0x00000001);
          firstName_ = "";
          bitField0_ = (bitField0_ & ~0x00000002);
          lastName_ = "";
          bitField0_ = (bitField0_ & ~0x00000004);
          return this;
        }

        @java.lang.Override
        public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
          return ar.com.moviecentral.dtos.Protos.internal_static_ar_com_moviecentral_dtos_MovieDTO_ActorDTO_descriptor;
        }

        @java.lang.Override
        public ar.com.moviecentral.dtos.Protos.MovieDTO.ActorDTO getDefaultInstanceForType() {
          return ar.com.moviecentral.dtos.Protos.MovieDTO.ActorDTO.getDefaultInstance();
        }

        @java.lang.Override
        public ar.com.moviecentral.dtos.Protos.MovieDTO.ActorDTO build() {
          ar.com.moviecentral.dtos.Protos.MovieDTO.ActorDTO result = buildPartial();
          if (!result.isInitialized()) {
            throw newUninitializedMessageException(result);
          }
          return result;
        }

        @java.lang.Override
        public ar.com.moviecentral.dtos.Protos.MovieDTO.ActorDTO buildPartial() {
          ar.com.moviecentral.dtos.Protos.MovieDTO.ActorDTO result = new ar.com.moviecentral.dtos.Protos.MovieDTO.ActorDTO(this);
          int from_bitField0_ = bitField0_;
          int to_bitField0_ = 0;
          if (((from_bitField0_ & 0x00000001) != 0)) {
            result.id_ = id_;
            to_bitField0_ |= 0x00000001;
          }
          if (((from_bitField0_ & 0x00000002) != 0)) {
            to_bitField0_ |= 0x00000002;
          }
          result.firstName_ = firstName_;
          if (((from_bitField0_ & 0x00000004) != 0)) {
            to_bitField0_ |= 0x00000004;
          }
          result.lastName_ = lastName_;
          result.bitField0_ = to_bitField0_;
          onBuilt();
          return result;
        }

        @java.lang.Override
        public Builder clone() {
          return super.clone();
        }
        @java.lang.Override
        public Builder setField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            java.lang.Object value) {
          return super.setField(field, value);
        }
        @java.lang.Override
        public Builder clearField(
            com.google.protobuf.Descriptors.FieldDescriptor field) {
          return super.clearField(field);
        }
        @java.lang.Override
        public Builder clearOneof(
            com.google.protobuf.Descriptors.OneofDescriptor oneof) {
          return super.clearOneof(oneof);
        }
        @java.lang.Override
        public Builder setRepeatedField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            int index, java.lang.Object value) {
          return super.setRepeatedField(field, index, value);
        }
        @java.lang.Override
        public Builder addRepeatedField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            java.lang.Object value) {
          return super.addRepeatedField(field, value);
        }
        @java.lang.Override
        public Builder mergeFrom(com.google.protobuf.Message other) {
          if (other instanceof ar.com.moviecentral.dtos.Protos.MovieDTO.ActorDTO) {
            return mergeFrom((ar.com.moviecentral.dtos.Protos.MovieDTO.ActorDTO)other);
          } else {
            super.mergeFrom(other);
            return this;
          }
        }

        public Builder mergeFrom(ar.com.moviecentral.dtos.Protos.MovieDTO.ActorDTO other) {
          if (other == ar.com.moviecentral.dtos.Protos.MovieDTO.ActorDTO.getDefaultInstance()) return this;
          if (other.hasId()) {
            setId(other.getId());
          }
          if (other.hasFirstName()) {
            bitField0_ |= 0x00000002;
            firstName_ = other.firstName_;
            onChanged();
          }
          if (other.hasLastName()) {
            bitField0_ |= 0x00000004;
            lastName_ = other.lastName_;
            onChanged();
          }
          this.mergeUnknownFields(other.unknownFields);
          onChanged();
          return this;
        }

        @java.lang.Override
        public final boolean isInitialized() {
          if (!hasId()) {
            return false;
          }
          if (!hasFirstName()) {
            return false;
          }
          if (!hasLastName()) {
            return false;
          }
          return true;
        }

        @java.lang.Override
        public Builder mergeFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
          ar.com.moviecentral.dtos.Protos.MovieDTO.ActorDTO parsedMessage = null;
          try {
            parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            parsedMessage = (ar.com.moviecentral.dtos.Protos.MovieDTO.ActorDTO) e.getUnfinishedMessage();
            throw e.unwrapIOException();
          } finally {
            if (parsedMessage != null) {
              mergeFrom(parsedMessage);
            }
          }
          return this;
        }
        private int bitField0_;

        private long id_ ;
        /**
         * <code>required int64 id = 1;</code>
         * @return Whether the id field is set.
         */
        public boolean hasId() {
          return ((bitField0_ & 0x00000001) != 0);
        }
        /**
         * <code>required int64 id = 1;</code>
         * @return The id.
         */
        public long getId() {
          return id_;
        }
        /**
         * <code>required int64 id = 1;</code>
         * @param value The id to set.
         * @return This builder for chaining.
         */
        public Builder setId(long value) {
          bitField0_ |= 0x00000001;
          id_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>required int64 id = 1;</code>
         * @return This builder for chaining.
         */
        public Builder clearId() {
          bitField0_ = (bitField0_ & ~0x00000001);
          id_ = 0L;
          onChanged();
          return this;
        }

        private java.lang.Object firstName_ = "";
        /**
         * <code>required string firstName = 2;</code>
         * @return Whether the firstName field is set.
         */
        public boolean hasFirstName() {
          return ((bitField0_ & 0x00000002) != 0);
        }
        /**
         * <code>required string firstName = 2;</code>
         * @return The firstName.
         */
        public java.lang.String getFirstName() {
          java.lang.Object ref = firstName_;
          if (!(ref instanceof java.lang.String)) {
            com.google.protobuf.ByteString bs =
                (com.google.protobuf.ByteString) ref;
            java.lang.String s = bs.toStringUtf8();
            if (bs.isValidUtf8()) {
              firstName_ = s;
            }
            return s;
          } else {
            return (java.lang.String) ref;
          }
        }
        /**
         * <code>required string firstName = 2;</code>
         * @return The bytes for firstName.
         */
        public com.google.protobuf.ByteString
            getFirstNameBytes() {
          java.lang.Object ref = firstName_;
          if (ref instanceof String) {
            com.google.protobuf.ByteString b = 
                com.google.protobuf.ByteString.copyFromUtf8(
                    (java.lang.String) ref);
            firstName_ = b;
            return b;
          } else {
            return (com.google.protobuf.ByteString) ref;
          }
        }
        /**
         * <code>required string firstName = 2;</code>
         * @param value The firstName to set.
         * @return This builder for chaining.
         */
        public Builder setFirstName(
            java.lang.String value) {
          if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
          firstName_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>required string firstName = 2;</code>
         * @return This builder for chaining.
         */
        public Builder clearFirstName() {
          bitField0_ = (bitField0_ & ~0x00000002);
          firstName_ = getDefaultInstance().getFirstName();
          onChanged();
          return this;
        }
        /**
         * <code>required string firstName = 2;</code>
         * @param value The bytes for firstName to set.
         * @return This builder for chaining.
         */
        public Builder setFirstNameBytes(
            com.google.protobuf.ByteString value) {
          if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
          firstName_ = value;
          onChanged();
          return this;
        }

        private java.lang.Object lastName_ = "";
        /**
         * <code>required string lastName = 3;</code>
         * @return Whether the lastName field is set.
         */
        public boolean hasLastName() {
          return ((bitField0_ & 0x00000004) != 0);
        }
        /**
         * <code>required string lastName = 3;</code>
         * @return The lastName.
         */
        public java.lang.String getLastName() {
          java.lang.Object ref = lastName_;
          if (!(ref instanceof java.lang.String)) {
            com.google.protobuf.ByteString bs =
                (com.google.protobuf.ByteString) ref;
            java.lang.String s = bs.toStringUtf8();
            if (bs.isValidUtf8()) {
              lastName_ = s;
            }
            return s;
          } else {
            return (java.lang.String) ref;
          }
        }
        /**
         * <code>required string lastName = 3;</code>
         * @return The bytes for lastName.
         */
        public com.google.protobuf.ByteString
            getLastNameBytes() {
          java.lang.Object ref = lastName_;
          if (ref instanceof String) {
            com.google.protobuf.ByteString b = 
                com.google.protobuf.ByteString.copyFromUtf8(
                    (java.lang.String) ref);
            lastName_ = b;
            return b;
          } else {
            return (com.google.protobuf.ByteString) ref;
          }
        }
        /**
         * <code>required string lastName = 3;</code>
         * @param value The lastName to set.
         * @return This builder for chaining.
         */
        public Builder setLastName(
            java.lang.String value) {
          if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
          lastName_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>required string lastName = 3;</code>
         * @return This builder for chaining.
         */
        public Builder clearLastName() {
          bitField0_ = (bitField0_ & ~0x00000004);
          lastName_ = getDefaultInstance().getLastName();
          onChanged();
          return this;
        }
        /**
         * <code>required string lastName = 3;</code>
         * @param value The bytes for lastName to set.
         * @return This builder for chaining.
         */
        public Builder setLastNameBytes(
            com.google.protobuf.ByteString value) {
          if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
          lastName_ = value;
          onChanged();
          return this;
        }
        @java.lang.Override
        public final Builder setUnknownFields(
            final com.google.protobuf.UnknownFieldSet unknownFields) {
          return super.setUnknownFields(unknownFields);
        }

        @java.lang.Override
        public final Builder mergeUnknownFields(
            final com.google.protobuf.UnknownFieldSet unknownFields) {
          return super.mergeUnknownFields(unknownFields);
        }


        // @@protoc_insertion_point(builder_scope:ar.com.moviecentral.dtos.MovieDTO.ActorDTO)
      }

      // @@protoc_insertion_point(class_scope:ar.com.moviecentral.dtos.MovieDTO.ActorDTO)
      private static final ar.com.moviecentral.dtos.Protos.MovieDTO.ActorDTO DEFAULT_INSTANCE;
      static {
        DEFAULT_INSTANCE = new ar.com.moviecentral.dtos.Protos.MovieDTO.ActorDTO();
      }

      public static ar.com.moviecentral.dtos.Protos.MovieDTO.ActorDTO getDefaultInstance() {
        return DEFAULT_INSTANCE;
      }

      @java.lang.Deprecated public static final com.google.protobuf.Parser<ActorDTO>
          PARSER = new com.google.protobuf.AbstractParser<ActorDTO>() {
        @java.lang.Override
        public ActorDTO parsePartialFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
          return new ActorDTO(input, extensionRegistry);
        }
      };

      public static com.google.protobuf.Parser<ActorDTO> parser() {
        return PARSER;
      }

      @java.lang.Override
      public com.google.protobuf.Parser<ActorDTO> getParserForType() {
        return PARSER;
      }

      @java.lang.Override
      public ar.com.moviecentral.dtos.Protos.MovieDTO.ActorDTO getDefaultInstanceForType() {
        return DEFAULT_INSTANCE;
      }

    }

    private int bitField0_;
    public static final int MOVIEID_FIELD_NUMBER = 1;
    private long movieId_;
    /**
     * <code>required int64 movieId = 1;</code>
     * @return Whether the movieId field is set.
     */
    public boolean hasMovieId() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>required int64 movieId = 1;</code>
     * @return The movieId.
     */
    public long getMovieId() {
      return movieId_;
    }

    public static final int TITLE_FIELD_NUMBER = 2;
    private volatile java.lang.Object title_;
    /**
     * <code>required string title = 2;</code>
     * @return Whether the title field is set.
     */
    public boolean hasTitle() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <code>required string title = 2;</code>
     * @return The title.
     */
    public java.lang.String getTitle() {
      java.lang.Object ref = title_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          title_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string title = 2;</code>
     * @return The bytes for title.
     */
    public com.google.protobuf.ByteString
        getTitleBytes() {
      java.lang.Object ref = title_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        title_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int DATE_FIELD_NUMBER = 3;
    private com.google.protobuf.Timestamp date_;
    /**
     * <code>required .google.protobuf.Timestamp date = 3;</code>
     * @return Whether the date field is set.
     */
    public boolean hasDate() {
      return ((bitField0_ & 0x00000004) != 0);
    }
    /**
     * <code>required .google.protobuf.Timestamp date = 3;</code>
     * @return The date.
     */
    public com.google.protobuf.Timestamp getDate() {
      return date_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : date_;
    }
    /**
     * <code>required .google.protobuf.Timestamp date = 3;</code>
     */
    public com.google.protobuf.TimestampOrBuilder getDateOrBuilder() {
      return date_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : date_;
    }

    public static final int ACTORS_FIELD_NUMBER = 4;
    private java.util.List<ar.com.moviecentral.dtos.Protos.MovieDTO.ActorDTO> actors_;
    /**
     * <code>repeated .ar.com.moviecentral.dtos.MovieDTO.ActorDTO actors = 4;</code>
     */
    public java.util.List<ar.com.moviecentral.dtos.Protos.MovieDTO.ActorDTO> getActorsList() {
      return actors_;
    }
    /**
     * <code>repeated .ar.com.moviecentral.dtos.MovieDTO.ActorDTO actors = 4;</code>
     */
    public java.util.List<? extends ar.com.moviecentral.dtos.Protos.MovieDTO.ActorDTOOrBuilder> 
        getActorsOrBuilderList() {
      return actors_;
    }
    /**
     * <code>repeated .ar.com.moviecentral.dtos.MovieDTO.ActorDTO actors = 4;</code>
     */
    public int getActorsCount() {
      return actors_.size();
    }
    /**
     * <code>repeated .ar.com.moviecentral.dtos.MovieDTO.ActorDTO actors = 4;</code>
     */
    public ar.com.moviecentral.dtos.Protos.MovieDTO.ActorDTO getActors(int index) {
      return actors_.get(index);
    }
    /**
     * <code>repeated .ar.com.moviecentral.dtos.MovieDTO.ActorDTO actors = 4;</code>
     */
    public ar.com.moviecentral.dtos.Protos.MovieDTO.ActorDTOOrBuilder getActorsOrBuilder(
        int index) {
      return actors_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasMovieId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasTitle()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasDate()) {
        memoizedIsInitialized = 0;
        return false;
      }
      for (int i = 0; i < getActorsCount(); i++) {
        if (!getActors(i).isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) != 0)) {
        output.writeInt64(1, movieId_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, title_);
      }
      if (((bitField0_ & 0x00000004) != 0)) {
        output.writeMessage(3, getDate());
      }
      for (int i = 0; i < actors_.size(); i++) {
        output.writeMessage(4, actors_.get(i));
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, movieId_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, title_);
      }
      if (((bitField0_ & 0x00000004) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, getDate());
      }
      for (int i = 0; i < actors_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(4, actors_.get(i));
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof ar.com.moviecentral.dtos.Protos.MovieDTO)) {
        return super.equals(obj);
      }
      ar.com.moviecentral.dtos.Protos.MovieDTO other = (ar.com.moviecentral.dtos.Protos.MovieDTO) obj;

      if (hasMovieId() != other.hasMovieId()) return false;
      if (hasMovieId()) {
        if (getMovieId()
            != other.getMovieId()) return false;
      }
      if (hasTitle() != other.hasTitle()) return false;
      if (hasTitle()) {
        if (!getTitle()
            .equals(other.getTitle())) return false;
      }
      if (hasDate() != other.hasDate()) return false;
      if (hasDate()) {
        if (!getDate()
            .equals(other.getDate())) return false;
      }
      if (!getActorsList()
          .equals(other.getActorsList())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasMovieId()) {
        hash = (37 * hash) + MOVIEID_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
            getMovieId());
      }
      if (hasTitle()) {
        hash = (37 * hash) + TITLE_FIELD_NUMBER;
        hash = (53 * hash) + getTitle().hashCode();
      }
      if (hasDate()) {
        hash = (37 * hash) + DATE_FIELD_NUMBER;
        hash = (53 * hash) + getDate().hashCode();
      }
      if (getActorsCount() > 0) {
        hash = (37 * hash) + ACTORS_FIELD_NUMBER;
        hash = (53 * hash) + getActorsList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static ar.com.moviecentral.dtos.Protos.MovieDTO parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ar.com.moviecentral.dtos.Protos.MovieDTO parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ar.com.moviecentral.dtos.Protos.MovieDTO parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ar.com.moviecentral.dtos.Protos.MovieDTO parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ar.com.moviecentral.dtos.Protos.MovieDTO parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ar.com.moviecentral.dtos.Protos.MovieDTO parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ar.com.moviecentral.dtos.Protos.MovieDTO parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static ar.com.moviecentral.dtos.Protos.MovieDTO parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static ar.com.moviecentral.dtos.Protos.MovieDTO parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static ar.com.moviecentral.dtos.Protos.MovieDTO parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static ar.com.moviecentral.dtos.Protos.MovieDTO parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static ar.com.moviecentral.dtos.Protos.MovieDTO parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(ar.com.moviecentral.dtos.Protos.MovieDTO prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code ar.com.moviecentral.dtos.MovieDTO}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:ar.com.moviecentral.dtos.MovieDTO)
        ar.com.moviecentral.dtos.Protos.MovieDTOOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return ar.com.moviecentral.dtos.Protos.internal_static_ar_com_moviecentral_dtos_MovieDTO_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return ar.com.moviecentral.dtos.Protos.internal_static_ar_com_moviecentral_dtos_MovieDTO_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                ar.com.moviecentral.dtos.Protos.MovieDTO.class, ar.com.moviecentral.dtos.Protos.MovieDTO.Builder.class);
      }

      // Construct using ar.com.moviecentral.dtos.Protos.MovieDTO.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getDateFieldBuilder();
          getActorsFieldBuilder();
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        movieId_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000001);
        title_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        if (dateBuilder_ == null) {
          date_ = null;
        } else {
          dateBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000004);
        if (actorsBuilder_ == null) {
          actors_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000008);
        } else {
          actorsBuilder_.clear();
        }
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return ar.com.moviecentral.dtos.Protos.internal_static_ar_com_moviecentral_dtos_MovieDTO_descriptor;
      }

      @java.lang.Override
      public ar.com.moviecentral.dtos.Protos.MovieDTO getDefaultInstanceForType() {
        return ar.com.moviecentral.dtos.Protos.MovieDTO.getDefaultInstance();
      }

      @java.lang.Override
      public ar.com.moviecentral.dtos.Protos.MovieDTO build() {
        ar.com.moviecentral.dtos.Protos.MovieDTO result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public ar.com.moviecentral.dtos.Protos.MovieDTO buildPartial() {
        ar.com.moviecentral.dtos.Protos.MovieDTO result = new ar.com.moviecentral.dtos.Protos.MovieDTO(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.movieId_ = movieId_;
          to_bitField0_ |= 0x00000001;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          to_bitField0_ |= 0x00000002;
        }
        result.title_ = title_;
        if (((from_bitField0_ & 0x00000004) != 0)) {
          if (dateBuilder_ == null) {
            result.date_ = date_;
          } else {
            result.date_ = dateBuilder_.build();
          }
          to_bitField0_ |= 0x00000004;
        }
        if (actorsBuilder_ == null) {
          if (((bitField0_ & 0x00000008) != 0)) {
            actors_ = java.util.Collections.unmodifiableList(actors_);
            bitField0_ = (bitField0_ & ~0x00000008);
          }
          result.actors_ = actors_;
        } else {
          result.actors_ = actorsBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof ar.com.moviecentral.dtos.Protos.MovieDTO) {
          return mergeFrom((ar.com.moviecentral.dtos.Protos.MovieDTO)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(ar.com.moviecentral.dtos.Protos.MovieDTO other) {
        if (other == ar.com.moviecentral.dtos.Protos.MovieDTO.getDefaultInstance()) return this;
        if (other.hasMovieId()) {
          setMovieId(other.getMovieId());
        }
        if (other.hasTitle()) {
          bitField0_ |= 0x00000002;
          title_ = other.title_;
          onChanged();
        }
        if (other.hasDate()) {
          mergeDate(other.getDate());
        }
        if (actorsBuilder_ == null) {
          if (!other.actors_.isEmpty()) {
            if (actors_.isEmpty()) {
              actors_ = other.actors_;
              bitField0_ = (bitField0_ & ~0x00000008);
            } else {
              ensureActorsIsMutable();
              actors_.addAll(other.actors_);
            }
            onChanged();
          }
        } else {
          if (!other.actors_.isEmpty()) {
            if (actorsBuilder_.isEmpty()) {
              actorsBuilder_.dispose();
              actorsBuilder_ = null;
              actors_ = other.actors_;
              bitField0_ = (bitField0_ & ~0x00000008);
              actorsBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getActorsFieldBuilder() : null;
            } else {
              actorsBuilder_.addAllMessages(other.actors_);
            }
          }
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        if (!hasMovieId()) {
          return false;
        }
        if (!hasTitle()) {
          return false;
        }
        if (!hasDate()) {
          return false;
        }
        for (int i = 0; i < getActorsCount(); i++) {
          if (!getActors(i).isInitialized()) {
            return false;
          }
        }
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        ar.com.moviecentral.dtos.Protos.MovieDTO parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (ar.com.moviecentral.dtos.Protos.MovieDTO) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private long movieId_ ;
      /**
       * <code>required int64 movieId = 1;</code>
       * @return Whether the movieId field is set.
       */
      public boolean hasMovieId() {
        return ((bitField0_ & 0x00000001) != 0);
      }
      /**
       * <code>required int64 movieId = 1;</code>
       * @return The movieId.
       */
      public long getMovieId() {
        return movieId_;
      }
      /**
       * <code>required int64 movieId = 1;</code>
       * @param value The movieId to set.
       * @return This builder for chaining.
       */
      public Builder setMovieId(long value) {
        bitField0_ |= 0x00000001;
        movieId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int64 movieId = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearMovieId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        movieId_ = 0L;
        onChanged();
        return this;
      }

      private java.lang.Object title_ = "";
      /**
       * <code>required string title = 2;</code>
       * @return Whether the title field is set.
       */
      public boolean hasTitle() {
        return ((bitField0_ & 0x00000002) != 0);
      }
      /**
       * <code>required string title = 2;</code>
       * @return The title.
       */
      public java.lang.String getTitle() {
        java.lang.Object ref = title_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            title_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string title = 2;</code>
       * @return The bytes for title.
       */
      public com.google.protobuf.ByteString
          getTitleBytes() {
        java.lang.Object ref = title_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          title_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string title = 2;</code>
       * @param value The title to set.
       * @return This builder for chaining.
       */
      public Builder setTitle(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        title_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string title = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearTitle() {
        bitField0_ = (bitField0_ & ~0x00000002);
        title_ = getDefaultInstance().getTitle();
        onChanged();
        return this;
      }
      /**
       * <code>required string title = 2;</code>
       * @param value The bytes for title to set.
       * @return This builder for chaining.
       */
      public Builder setTitleBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        title_ = value;
        onChanged();
        return this;
      }

      private com.google.protobuf.Timestamp date_;
      private com.google.protobuf.SingleFieldBuilderV3<
          com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> dateBuilder_;
      /**
       * <code>required .google.protobuf.Timestamp date = 3;</code>
       * @return Whether the date field is set.
       */
      public boolean hasDate() {
        return ((bitField0_ & 0x00000004) != 0);
      }
      /**
       * <code>required .google.protobuf.Timestamp date = 3;</code>
       * @return The date.
       */
      public com.google.protobuf.Timestamp getDate() {
        if (dateBuilder_ == null) {
          return date_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : date_;
        } else {
          return dateBuilder_.getMessage();
        }
      }
      /**
       * <code>required .google.protobuf.Timestamp date = 3;</code>
       */
      public Builder setDate(com.google.protobuf.Timestamp value) {
        if (dateBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          date_ = value;
          onChanged();
        } else {
          dateBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000004;
        return this;
      }
      /**
       * <code>required .google.protobuf.Timestamp date = 3;</code>
       */
      public Builder setDate(
          com.google.protobuf.Timestamp.Builder builderForValue) {
        if (dateBuilder_ == null) {
          date_ = builderForValue.build();
          onChanged();
        } else {
          dateBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000004;
        return this;
      }
      /**
       * <code>required .google.protobuf.Timestamp date = 3;</code>
       */
      public Builder mergeDate(com.google.protobuf.Timestamp value) {
        if (dateBuilder_ == null) {
          if (((bitField0_ & 0x00000004) != 0) &&
              date_ != null &&
              date_ != com.google.protobuf.Timestamp.getDefaultInstance()) {
            date_ =
              com.google.protobuf.Timestamp.newBuilder(date_).mergeFrom(value).buildPartial();
          } else {
            date_ = value;
          }
          onChanged();
        } else {
          dateBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000004;
        return this;
      }
      /**
       * <code>required .google.protobuf.Timestamp date = 3;</code>
       */
      public Builder clearDate() {
        if (dateBuilder_ == null) {
          date_ = null;
          onChanged();
        } else {
          dateBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }
      /**
       * <code>required .google.protobuf.Timestamp date = 3;</code>
       */
      public com.google.protobuf.Timestamp.Builder getDateBuilder() {
        bitField0_ |= 0x00000004;
        onChanged();
        return getDateFieldBuilder().getBuilder();
      }
      /**
       * <code>required .google.protobuf.Timestamp date = 3;</code>
       */
      public com.google.protobuf.TimestampOrBuilder getDateOrBuilder() {
        if (dateBuilder_ != null) {
          return dateBuilder_.getMessageOrBuilder();
        } else {
          return date_ == null ?
              com.google.protobuf.Timestamp.getDefaultInstance() : date_;
        }
      }
      /**
       * <code>required .google.protobuf.Timestamp date = 3;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> 
          getDateFieldBuilder() {
        if (dateBuilder_ == null) {
          dateBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder>(
                  getDate(),
                  getParentForChildren(),
                  isClean());
          date_ = null;
        }
        return dateBuilder_;
      }

      private java.util.List<ar.com.moviecentral.dtos.Protos.MovieDTO.ActorDTO> actors_ =
        java.util.Collections.emptyList();
      private void ensureActorsIsMutable() {
        if (!((bitField0_ & 0x00000008) != 0)) {
          actors_ = new java.util.ArrayList<ar.com.moviecentral.dtos.Protos.MovieDTO.ActorDTO>(actors_);
          bitField0_ |= 0x00000008;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          ar.com.moviecentral.dtos.Protos.MovieDTO.ActorDTO, ar.com.moviecentral.dtos.Protos.MovieDTO.ActorDTO.Builder, ar.com.moviecentral.dtos.Protos.MovieDTO.ActorDTOOrBuilder> actorsBuilder_;

      /**
       * <code>repeated .ar.com.moviecentral.dtos.MovieDTO.ActorDTO actors = 4;</code>
       */
      public java.util.List<ar.com.moviecentral.dtos.Protos.MovieDTO.ActorDTO> getActorsList() {
        if (actorsBuilder_ == null) {
          return java.util.Collections.unmodifiableList(actors_);
        } else {
          return actorsBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .ar.com.moviecentral.dtos.MovieDTO.ActorDTO actors = 4;</code>
       */
      public int getActorsCount() {
        if (actorsBuilder_ == null) {
          return actors_.size();
        } else {
          return actorsBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .ar.com.moviecentral.dtos.MovieDTO.ActorDTO actors = 4;</code>
       */
      public ar.com.moviecentral.dtos.Protos.MovieDTO.ActorDTO getActors(int index) {
        if (actorsBuilder_ == null) {
          return actors_.get(index);
        } else {
          return actorsBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .ar.com.moviecentral.dtos.MovieDTO.ActorDTO actors = 4;</code>
       */
      public Builder setActors(
          int index, ar.com.moviecentral.dtos.Protos.MovieDTO.ActorDTO value) {
        if (actorsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureActorsIsMutable();
          actors_.set(index, value);
          onChanged();
        } else {
          actorsBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .ar.com.moviecentral.dtos.MovieDTO.ActorDTO actors = 4;</code>
       */
      public Builder setActors(
          int index, ar.com.moviecentral.dtos.Protos.MovieDTO.ActorDTO.Builder builderForValue) {
        if (actorsBuilder_ == null) {
          ensureActorsIsMutable();
          actors_.set(index, builderForValue.build());
          onChanged();
        } else {
          actorsBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .ar.com.moviecentral.dtos.MovieDTO.ActorDTO actors = 4;</code>
       */
      public Builder addActors(ar.com.moviecentral.dtos.Protos.MovieDTO.ActorDTO value) {
        if (actorsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureActorsIsMutable();
          actors_.add(value);
          onChanged();
        } else {
          actorsBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .ar.com.moviecentral.dtos.MovieDTO.ActorDTO actors = 4;</code>
       */
      public Builder addActors(
          int index, ar.com.moviecentral.dtos.Protos.MovieDTO.ActorDTO value) {
        if (actorsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureActorsIsMutable();
          actors_.add(index, value);
          onChanged();
        } else {
          actorsBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .ar.com.moviecentral.dtos.MovieDTO.ActorDTO actors = 4;</code>
       */
      public Builder addActors(
          ar.com.moviecentral.dtos.Protos.MovieDTO.ActorDTO.Builder builderForValue) {
        if (actorsBuilder_ == null) {
          ensureActorsIsMutable();
          actors_.add(builderForValue.build());
          onChanged();
        } else {
          actorsBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .ar.com.moviecentral.dtos.MovieDTO.ActorDTO actors = 4;</code>
       */
      public Builder addActors(
          int index, ar.com.moviecentral.dtos.Protos.MovieDTO.ActorDTO.Builder builderForValue) {
        if (actorsBuilder_ == null) {
          ensureActorsIsMutable();
          actors_.add(index, builderForValue.build());
          onChanged();
        } else {
          actorsBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .ar.com.moviecentral.dtos.MovieDTO.ActorDTO actors = 4;</code>
       */
      public Builder addAllActors(
          java.lang.Iterable<? extends ar.com.moviecentral.dtos.Protos.MovieDTO.ActorDTO> values) {
        if (actorsBuilder_ == null) {
          ensureActorsIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, actors_);
          onChanged();
        } else {
          actorsBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .ar.com.moviecentral.dtos.MovieDTO.ActorDTO actors = 4;</code>
       */
      public Builder clearActors() {
        if (actorsBuilder_ == null) {
          actors_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000008);
          onChanged();
        } else {
          actorsBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .ar.com.moviecentral.dtos.MovieDTO.ActorDTO actors = 4;</code>
       */
      public Builder removeActors(int index) {
        if (actorsBuilder_ == null) {
          ensureActorsIsMutable();
          actors_.remove(index);
          onChanged();
        } else {
          actorsBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .ar.com.moviecentral.dtos.MovieDTO.ActorDTO actors = 4;</code>
       */
      public ar.com.moviecentral.dtos.Protos.MovieDTO.ActorDTO.Builder getActorsBuilder(
          int index) {
        return getActorsFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .ar.com.moviecentral.dtos.MovieDTO.ActorDTO actors = 4;</code>
       */
      public ar.com.moviecentral.dtos.Protos.MovieDTO.ActorDTOOrBuilder getActorsOrBuilder(
          int index) {
        if (actorsBuilder_ == null) {
          return actors_.get(index);  } else {
          return actorsBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .ar.com.moviecentral.dtos.MovieDTO.ActorDTO actors = 4;</code>
       */
      public java.util.List<? extends ar.com.moviecentral.dtos.Protos.MovieDTO.ActorDTOOrBuilder> 
           getActorsOrBuilderList() {
        if (actorsBuilder_ != null) {
          return actorsBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(actors_);
        }
      }
      /**
       * <code>repeated .ar.com.moviecentral.dtos.MovieDTO.ActorDTO actors = 4;</code>
       */
      public ar.com.moviecentral.dtos.Protos.MovieDTO.ActorDTO.Builder addActorsBuilder() {
        return getActorsFieldBuilder().addBuilder(
            ar.com.moviecentral.dtos.Protos.MovieDTO.ActorDTO.getDefaultInstance());
      }
      /**
       * <code>repeated .ar.com.moviecentral.dtos.MovieDTO.ActorDTO actors = 4;</code>
       */
      public ar.com.moviecentral.dtos.Protos.MovieDTO.ActorDTO.Builder addActorsBuilder(
          int index) {
        return getActorsFieldBuilder().addBuilder(
            index, ar.com.moviecentral.dtos.Protos.MovieDTO.ActorDTO.getDefaultInstance());
      }
      /**
       * <code>repeated .ar.com.moviecentral.dtos.MovieDTO.ActorDTO actors = 4;</code>
       */
      public java.util.List<ar.com.moviecentral.dtos.Protos.MovieDTO.ActorDTO.Builder> 
           getActorsBuilderList() {
        return getActorsFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          ar.com.moviecentral.dtos.Protos.MovieDTO.ActorDTO, ar.com.moviecentral.dtos.Protos.MovieDTO.ActorDTO.Builder, ar.com.moviecentral.dtos.Protos.MovieDTO.ActorDTOOrBuilder> 
          getActorsFieldBuilder() {
        if (actorsBuilder_ == null) {
          actorsBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              ar.com.moviecentral.dtos.Protos.MovieDTO.ActorDTO, ar.com.moviecentral.dtos.Protos.MovieDTO.ActorDTO.Builder, ar.com.moviecentral.dtos.Protos.MovieDTO.ActorDTOOrBuilder>(
                  actors_,
                  ((bitField0_ & 0x00000008) != 0),
                  getParentForChildren(),
                  isClean());
          actors_ = null;
        }
        return actorsBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:ar.com.moviecentral.dtos.MovieDTO)
    }

    // @@protoc_insertion_point(class_scope:ar.com.moviecentral.dtos.MovieDTO)
    private static final ar.com.moviecentral.dtos.Protos.MovieDTO DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new ar.com.moviecentral.dtos.Protos.MovieDTO();
    }

    public static ar.com.moviecentral.dtos.Protos.MovieDTO getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<MovieDTO>
        PARSER = new com.google.protobuf.AbstractParser<MovieDTO>() {
      @java.lang.Override
      public MovieDTO parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new MovieDTO(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<MovieDTO> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<MovieDTO> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public ar.com.moviecentral.dtos.Protos.MovieDTO getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ar_com_moviecentral_dtos_MovieDTO_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ar_com_moviecentral_dtos_MovieDTO_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ar_com_moviecentral_dtos_MovieDTO_ActorDTO_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ar_com_moviecentral_dtos_MovieDTO_ActorDTO_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\tdtos.prot\022\030ar.com.moviecentral.dtos\032\037g" +
      "oogle/protobuf/timestamp.proto\"\316\001\n\010Movie" +
      "DTO\022\017\n\007movieId\030\001 \002(\003\022\r\n\005title\030\002 \002(\t\022(\n\004d" +
      "ate\030\003 \002(\0132\032.google.protobuf.Timestamp\022;\n" +
      "\006actors\030\004 \003(\0132+.ar.com.moviecentral.dtos" +
      ".MovieDTO.ActorDTO\032;\n\010ActorDTO\022\n\n\002id\030\001 \002" +
      "(\003\022\021\n\tfirstName\030\002 \002(\t\022\020\n\010lastName\030\003 \002(\tB" +
      "\"\n\030ar.com.moviecentral.dtosB\006Protos"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.TimestampProto.getDescriptor(),
        });
    internal_static_ar_com_moviecentral_dtos_MovieDTO_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_ar_com_moviecentral_dtos_MovieDTO_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ar_com_moviecentral_dtos_MovieDTO_descriptor,
        new java.lang.String[] { "MovieId", "Title", "Date", "Actors", });
    internal_static_ar_com_moviecentral_dtos_MovieDTO_ActorDTO_descriptor =
      internal_static_ar_com_moviecentral_dtos_MovieDTO_descriptor.getNestedTypes().get(0);
    internal_static_ar_com_moviecentral_dtos_MovieDTO_ActorDTO_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ar_com_moviecentral_dtos_MovieDTO_ActorDTO_descriptor,
        new java.lang.String[] { "Id", "FirstName", "LastName", });
    com.google.protobuf.TimestampProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
